name: expense_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  googleapis: ^11.4.0
  intl: ^0.18.1
  uuid: ^4.2.1
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.24.2
  http: ^1.2.2
  google_api_availability: ^3.0.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_launcher_icons: ^0.14.1
  flutter_slidable: ^3.1.1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

