# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# Add this line
pod 'GoogleUtilities', :modular_headers => true
pod 'GoogleUtilities/Environment', :modular_headers => true
pod 'GoogleUtilities/Logger', :modular_headers => true
pod 'GoogleUtilities/Network', :modular_headers => true
pod 'GoogleUtilities/UserDefaults', :modular_headers => true

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Add the following configurations
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      
      # Include the appropriate configuration file
      if config.name == 'Debug'
        config.base_configuration_reference = installer.pods_project.files.find { |f| f.path == 'Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' }
      elsif config.name == 'Profile'
        config.base_configuration_reference = installer.pods_project.files.find { |f| f.path == 'Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig' }
      elsif config.name == 'Release'
        config.base_configuration_reference = installer.pods_project.files.find { |f| f.path == 'Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig' }
      end
      
      # Add this line:
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
